contour_lines:
  jshead: [js/d3.v3.js]
  css: [css/contours.css]
  cdn:
    jshead: 
      - "http://d3js.org/d3.v3.min.js"
    css:
      - "http://timelyportfolio.github.io/rChartsExtra/contours.css"

