catcorrjs:
  jshead: [js/d3.v3.min.js, js/crossfilter.min.js, js/catcorr.min.js, js/d3.tip.min.js]
  css: [css/catcorr.css]
  cdn:
    jshead: 
      - http://d3js.org/d3.v3.min.js
      - http://timelyportfolio.github.io/rCharts_extra/catcorrjs/js/crossfilter.min.js
      - http://timelyportfolio.github.io/rCharts_extra/catcorrjs/js/catcorr.min.js
      - http://timelyportfolio.github.io/rCharts_extra/catcorrjs/js/d3.tip.min.js
    css: http://timelyportfolio.github.io/rCharts_extra/catcorrjs/css/catcorr.css
